// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "./internal/domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tailnet$0 from "./internal/tailnet/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as transfer$0 from "./internal/transfer/models.js";

export function AddTrustedDevice(name: string, token: string): $CancellablePromise<domain$0.TrustedDevice> {
    return $Call.ByID(77881618, name, token);
}

export function ConnectService(req: tailnet$0.ConnectServiceRequest): $CancellablePromise<domain$0.Session> {
    return $Call.ByID(1010473179, req);
}

export function ConnectTrustedService(deviceID: string, label: string, remotePort: number, localPort: number, serviceType: string): $CancellablePromise<domain$0.Session> {
    return $Call.ByID(265948694, deviceID, label, remotePort, localPort, serviceType);
}

export function InspectFileOffer(token: string): $CancellablePromise<domain$0.FileManifest> {
    return $Call.ByID(995657534, token);
}

export function InspectTrustedFileOffer(deviceID: string): $CancellablePromise<domain$0.FileManifest> {
    return $Call.ByID(3232435551, deviceID);
}

export function ParseServiceInvite(value: string): $CancellablePromise<domain$0.ServiceInvite> {
    return $Call.ByID(561645253, value);
}

export function PauseTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3115319327, id);
}

export function ReceiveFiles(req: transfer$0.ReceiveRequest): $CancellablePromise<domain$0.Transfer> {
    return $Call.ByID(2555218918, req);
}

export function ReceiveTrustedFiles(deviceID: string, req: transfer$0.ReceiveRequest): $CancellablePromise<domain$0.Transfer> {
    return $Call.ByID(1678096389, deviceID, req);
}

export function RemoveTrustedDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(2638453931, id);
}

export function ResumeTransfer(id: string): $CancellablePromise<void> {
    return $Call.ByID(907302374, id);
}

export function ShareService(req: tailnet$0.ShareServiceRequest): $CancellablePromise<domain$0.Session> {
    return $Call.ByID(1415449648, req);
}

export function Snapshot(): $CancellablePromise<domain$0.Snapshot> {
    return $Call.ByID(3423517222);
}

export function StartFileOffer(req: transfer$0.StartOfferRequest): $CancellablePromise<domain$0.Session> {
    return $Call.ByID(1045876434, req);
}

export function StopSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3505525398, id);
}

export function TakePendingServiceInvite(): $CancellablePromise<string> {
    return $Call.ByID(99441782);
}
