// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ReceiveRequest {
    "token": string;
    "destination": string;
    "selected": string[] | null;
    "collision": string;
}

export interface StartOfferRequest {
    "paths": string[] | null;
    "label": string;
    "persistent": boolean;
}
