// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ConnectServiceRequest {
    "label": string;
    "token": string;
    "remotePort": number;
    "localPort": number;
}

export interface ShareServiceRequest {
    "label": string;
    "localHost": string;
    "localPort": number;
    "remotePort": number;
    "persistent": boolean;
}
