// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface FileEntry {
    "path": string;
    "size": number;
    "modTimeUnixNano": number;
    "sha256": string;
}

export interface FileManifest {
    "protocolVersion": number;
    "transferId": string;
    "label": string;
    "files": FileEntry[] | null;
    "totalBytes": number;
    "cliCompatible": boolean;
}

export interface ServiceInvite {
    "token": string;
    "remotePort": number;
    "label": string;
    "serviceType": string;
}

export interface Session {
    "id": string;
    "kind": SessionKind;
    "label": string;
    "state": string;
    "token"?: string;
    "localAddress"?: string;
    "remotePort"?: number;
    "transport"?: string;
    "invite"?: string;
    "serviceType"?: string;
    "latencyMs"?: number;
    "persistent": boolean;
    "cliCompatible": boolean;
    "createdAt": string;
    "error"?: string;
}

export enum SessionKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SessionServiceShare = "service-share",
    SessionServiceLink = "service-link",
    SessionFileOffer = "file-offer",
};

export interface Snapshot {
    "sessions": Session[] | null;
    "transfers": Transfer[] | null;
    "trustedDevices": TrustedDevice[] | null;
}

export interface Transfer {
    "id": string;
    "direction": TransferDirection;
    "label": string;
    "state": string;
    "token"?: string;
    "destination"?: string;
    "filesTotal": number;
    "filesCompleted": number;
    "bytesTotal": number;
    "bytesTransferred": number;
    "error"?: string;
    "createdAt": string;
    "updatedAt": string;
}

export enum TransferDirection {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TransferSend = "send",
    TransferReceive = "receive",
};

export interface TrustedDevice {
    "id": string;
    "name": string;
    "tokenHint": string;
    "createdAt": string;
    "lastUsed"?: string;
}
